/*
 * BetterDiscord Plugin Loader
 * This file is auto-generated by the build system to load .plugin.js files
 */

import { BDPluginManager } from "./PluginManager";
import { Logger } from "@utils/Logger";

const logger = new Logger("BDPluginLoader", "#ff7373");

// This function is called by the auto-generated plugin loader
export function registerBDPlugin(pluginCode: string, fileName: string): void {
    try {
        const plugin = BDPluginManager.loadPlugin(fileName, pluginCode);
        if (plugin) {
            logger.info(`Registered: ${plugin.meta.name}`);
        }
    } catch (error) {
        logger.error(`Failed to register plugin ${fileName}:`, error);
    }
}

// Export a function to initialize all BD plugins
export function initializeBDPlugins(): void {
    logger.info("Initializing BetterDiscord plugins...");
    BDPluginManager.loadAllPlugins();
}
