#!/usr/bin/env node
/*
 * BetterDiscord Plugin Loader for Testcord
 * This script loads .plugin.js files and makes them available to the build system
 */

import { readdir, readFile } from "fs/promises";
import { join, resolve } from "path";
import { existsSync } from "fs";
import { writeFileSync } from "fs";

const BD_PLUGINS_DIR = join(process.cwd(), "src", "Betterdiscordplugins");
const OUTPUT_FILE = join(BD_PLUGINS_DIR, "bundledPlugins.ts");

async function loadBDPlugins() {
    if (!existsSync(BD_PLUGINS_DIR)) {
        console.log("BetterDiscord plugins directory does not exist yet");
        writeFileSync(
            OUTPUT_FILE,
            "// No BD plugins loaded yet\nexport const bundledPlugins: Array<{name: string; code: string; file: string}> = [];\nexport const BDPluginMeta: Record<string, { folderName: string; userPlugin: boolean }> = {};\n",
        );
        return;
    }

    const files = await readdir(BD_PLUGINS_DIR);
    const pluginFiles = files.filter(
        (f) => f.endsWith(".plugin.js") && f !== "bundledPlugins.ts",
    );

    let output = `// Auto-generated BetterDiscord plugin bundle\n// Do not edit this file manually\n\n`;
    output += `export const bundledPlugins: Array<{name: string; code: string; file: string}> = [\n`;

    let metaOutput = `// Auto-generated BetterDiscord plugin metadata\n// Do not edit this file manually\n\n`;
    metaOutput += `export const BDPluginMeta: Record<string, { folderName: string; userPlugin: boolean }> = {\n`;

    for (const file of pluginFiles) {
        try {
            const filePath = join(BD_PLUGINS_DIR, file);
            const content = await readFile(filePath, "utf-8");

            // Escape the content for embedding in TypeScript
            const escapedContent = content
                .replace(/\\/g, "\\\\")
                .replace(/`/g, "\\`")
                .replace(/\$\{/g, "\\${");

            // Extract plugin name from metadata
            const nameMatch = content.match(/@(?:name|Name)\s+([^\n\r*]+)/);
            const pluginName = nameMatch
                ? nameMatch[1].trim()
                : file.replace(/\.plugin\.js$/i, "");
            const safeName = pluginName.replace(/\s+/g, "_");

            output += `  { name: ${JSON.stringify(pluginName)}, code: \`${escapedContent}\`, file: ${JSON.stringify(file)} },\n`;

            // Add metadata entry - BD plugins are NOT user plugins
            metaOutput += `  ${JSON.stringify(safeName)}: { folderName: "src/Betterdiscordplugins/${file}", userPlugin: false },\n`;

            console.log(`Loaded BD plugin: ${pluginName}`);
        } catch (error) {
            console.error(`Failed to load plugin ${file}:`, error);
        }
    }

    output += `];\n`;
    metaOutput += `};\n`;

    writeFileSync(OUTPUT_FILE, output + "\n" + metaOutput);
    console.log(
        `\nBundled ${pluginFiles.length} BetterDiscord plugin(s) into bundledPlugins.ts`,
    );
}

loadBDPlugins().catch(console.error);
